### PR TITLE
Feature/clubhouse

### PR DESCRIPTION
**Pull request by oxenprogrammer**
## What this Pull Request does :

- Use Devise gem to manage member authentication. (Sign Up and Login)
- Enable Guest Users to View Post
- Enable only authenticated members to create new posts.
- Enable only authenticated members to see post authors.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Status: Changes Required :red_circle: 

Hello @oxenprogrammer, you have done great job so far :muscle:, but there are some changes that need to be implemented, you can find them below :arrow_down: 
- [x] For future cases please be reminded that you should make your development branch your default one, and open the pull request from the feature branch to the development branch
- [x] Whenever I try to create a post and the post that I write is under 50 characters so I get the error message until now everything is okay, but after that when I increase the number of characters and reach the limit I see that I cannot click the `Create Post` button and neither `back` button, kindly fix this
- [x] Your route should use only these resources :posts, only: [:new, :create, :index] ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)) 
- [x] Your posts controller/new should initializes an empty post `@post = Post.new` [ ] ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- [x] Remove all the logic from the views. The view should be only for rendering, instead use the helpers to put your logic

### Please implement these changes and ask for another code review whenever you are ready

_**If you have any question related to the required changes feel free to text me on slack @GzimAsani** or just add a comment here_

HAPPY CODING :computer: :desktop_computer:

**Comment by oxenprogrammer** [comment]
@GzimAsani , thank you for your review. Could you please clarify on this? `Your posts controller/new should initializes an empty post @post = Post.new [ ] (screenshot from Odin)`. Since in my controller I have 
 ```
 def new
    @post = current_user.posts.build
 end
  ```
Which initializes an empty post requiring authentication though.

**Comment by oxenprogrammer** [comment]
`Whenever I try to create a post and the post that I write is under 50 characters so I get the error message until now everything is okay, but after that when I increase the number of characters and reach the limit I see that I cannot click the Create Post button and neither back button, kindly fix this` May you please reproduce this bug or send a screenshot of exactly what happens? Everything seems to work well on my side @GzimAsani

**Comment by GzimAsani** [comment]
Hei, @oxenprogrammer do you have time for zoom, I will show you

**Comment by oxenprogrammer** [comment]
@GzimAsani  Yes I do

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- [x] As I can see, you worked on the previous TSE's recommendation. :+1:
- [x] I like your design. :100: 
- [x] I can create posts :1st_place_medal: 
- [x] I can sign in / sign out :+1: 

To Improve :factory_worker:

- [ ] Our posts controller/new should initializes an empty post @post = Post.new  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

- [ ] It will be perfect if you remove logic in your view and put it in your helpers. As a developer your job is to create quality code that solves your client’s problems. Quality has many aspects to it, including readability and maintainability. It is much easier to read code that is lean and skinny, as well as serving a single purpose. When you look at a CSS file, you know it’s for styling and giving your site personality and uniqueness. When you look at a JavaScript file, you know it handles the interactivity on the front-end for the person viewing the site. And the view file is responsible for the HTML.


- [x] As I can see, your inline comments are helpful and make your code easy to read, but I suggest you focus on your code and logic. Using git history can help us to understand what you have done and  to review a previous version of your code, please, feel free to remove them.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Comment by oxenprogrammer** [comment]
psot-new
@rindrajosia , Thanks for your review. There are two ways of doing this, 
 ```
 def new
    @post = Post.new
end
  ```
which will initialize an empty post but will not utilize Devise way of requiring authentication at the beginning.
`And then there is this way` 
 ```
 def new
    @post = current_user.posts.build
 end
  ```
which will also initialize an empty post but will require that the user is first authenticated, thus redirecting the user first to either signup or login.

I could use the former but that won't adhere to `DRY` as I will have to write a helper method to check if user is loggedin and get current_user before posting. I had the same discussion with @GzimAsani.

They both meet the requirement but the latter does a lot of heavy liftings. I hope we are on the same page. Gracias

**Comment by oxenprogrammer** [comment]
@rindrajosia 
logic-view
I moved all view logic *created by me* to the `helper class` However, there are view related logic auto generated by `Devise gem`  I  don't think it is necessary for me to rewrite all that code, just assume this is a large enterprise app with millions of line of code and I have used several gems that have `view related logic` like `Devise gem`. Will I be required to rewrite all that logic? I guess no, it will beat the purpose of **fast development and deployment**.  I want to hear your thoughts on that and other **Code Reviewers**

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Pull request merged**
